---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_tflint

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.20.0
    hooks:
      - id: terraform-docs-system
        args: ["./modules/model"]
      - id: terraform-docs-system
        args: ["./modules/model/examples/model_file"]
      - id: terraform-docs-system
        args: ["./examples/system"]
      - id: terraform-docs-system
        args: ["."]
